### ISSUE TITLE
configparser usage not python 2 compliant

### ISSUE THREAD

**Issue by asteriske** [asteriske/translogrify#4]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-wOfylF-build/setup.py", line 63, in <module>
    create.write_new_config()
  File "translogrify/create.py", line 18, in write_new_config
    'email_requires_login':'True'
AttributeError: ConfigParser instance has no attribute '__setitem__'

See: https://stackoverflow.com/questions/39544331/configparser-instance-has-no-attribute-setitem

**Comment by asteriske** [comment]
Addressed in 6090f6d29470a960b025c953836d0acaba2fe84e
